version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cur3P@ssW0rd!
    volumes:
      -  /home/publish/db/   #modified for VM 
    
  rungroopwebapp:
    image: final
    container_name: rungroopwebapp
    restart: always
    build:
      context: .
    ports:
       - "8009:80"
    depends_on: 
       -  db
    volumes: /home/publish/src #added for VM

  db-management:
    image: sqlpad/sqlpad
    container_name: sqlpad
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: 'admin@sqlpad.com'
      SQLPAD_ADMIN_PASSWORD: 'admin'
      SQLPAD_CONNECTIONS_mssqlserver_name: rungroopwebapp
      SQLPAD_CONNECTIONS_mssqlserver_driver: sqlserver
      SQLPAD_CONNECTIONS_mssqlserver_database: RunGroops
      SQLPAD_CONNECTIONS_mssqlserver_username: sa
      SQLPAD_CONNECTIONS_mssqlserver_password: S3cur3P@ssW0rd!
    volumes:
      - /home/publish/sqlpad/   #modfied for VM 